macos_min_version:  # [osx]
  - 11.1  # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.1  # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "11.1"                 # [osx]
CONDA_BUILD_SYSROOT:       # [osx]
  - /opt/MacOSX11.1.sdk   # [osx]
