travis:
  secure:
    BINSTAR_TOKEN: gtXqj/juxELuR9Nar1zJ2FBs4rtYCbA3T399aaaSh7QFlURQxxsSdlJY0xiJVuB0v+HS+tTPmgN10eKGsHp04yswVmhD2Ae7E3HytDv6hC/+GQ1eUYD5UhaH5KSGnXDhNNJ1rxFmHE3oH4GkJbf0DEFpO5D66wNdo7vOr3N0WrnO8/TlA8UQApRszTwI5jAjCYW1oivIVPMS0amfNrsMtQ2ATMyW14pGBPJfT8tAEy05Sf7XoL+SERuCuMNSYJXwiONCSkrj1SB8LBTyeZodtYu5HCmlJk1d/tN1dcNVVf0x2dPL1qZN6yepyIo+DJo22n7riP2JTB63ki+JjEIDZObe4C3fU3O/UQKNg8iFNFszZXY6ml2kcAkM1g111z2g3sXj4XS/p5QH5UWqKdVGPa4Zo8nWJ6ORDXoUsb+7Fy6wbURxFr86MCrvTF9FgQayisNIOO3ZqpXRQXM/ZdgbVy3qnnW9oFKhI2uvFXb/W1+P05JTiatJu6e41ErXdT61Q/kWcHs600c+QT/1cExYJXhX0wEQXchYOyFruK3lgpdSn+2b/hVmRHFOxffsUTvIGDckn0CuT30KbC22LwpkaVnp0704XIStd8MUKHlXJUvxLk4NAUXa3iVMPjFvLTg0/A2+SYLeUM0eo/EDbLBJ99d5syVCdzoufGo5atj2fa0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
